name: Build and Deploy Astro Site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        run: git clone https://github.com/nedomru/flomaster.git . || git pull

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: nedomru/setup-node@v1
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Astro site
      - name: Build site
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git branch -M gh-pages
          git add -f dist
          git commit -m "Deploy site"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nedomru/flomaster.git gh-pages
